# Generated by Django 5.1.4 on 2025-01-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numberofblogs',
            field=models.IntegerField(default=0),
        ),
    ]
