# Generated by Django 5.1.4 on 2025-01-30 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
