# Generated by Django 5.1.4 on 2025-01-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
