# Generated by Django 5.1.4 on 2025-02-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
