# Generated by Django 5.1.4 on 2025-01-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_post_description_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
